// <auto-generated />
using System;
using ACMEncuesta.ddd.Infraestructura.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ACMEncuesta.ddd.Infraestructura.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220604202519_Mod_AgregarEncuestaCamposId")]
    partial class Mod_AgregarEncuestaCamposId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ACMEncuenta.ddd.Dominio.Entidades.Encuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CantidadUsuarios")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Encuesta", "dbo");
                });

            modelBuilder.Entity("ACMEncuenta.ddd.Dominio.Entidades.EncuestaCampos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("EncuestaId")
                        .HasColumnType("int");

                    b.Property<string>("Requerido")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("TipoCampo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EncuestaId");

                    b.ToTable("EncuestaCampo", "dbo");
                });

            modelBuilder.Entity("ACMEncuenta.ddd.Dominio.Entidades.EncuestaCamposValor", b =>
                {
                    b.Property<int>("EncuestaId")
                        .HasColumnType("int");

                    b.Property<int>("EncuestaCamposId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoPK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EncuestaCodigosCodigoPK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("EncuestaCodigosEncuestaId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EncuestaId", "EncuestaCamposId", "CodigoPK");

                    b.HasIndex("EncuestaCamposId");

                    b.HasIndex("EncuestaCodigosEncuestaId", "EncuestaCodigosCodigoPK");

                    b.ToTable("EncuestaCamposValor", "dbo");
                });

            modelBuilder.Entity("ACMEncuenta.ddd.Dominio.Entidades.EncuestaCodigos", b =>
                {
                    b.Property<int>("EncuestaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoPK")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EncuestaId", "CodigoPK");

                    b.ToTable("EncuestaCodigos", "dbo");
                });

            modelBuilder.Entity("ACMEncuenta.ddd.Dominio.Entidades.EncuestaCampos", b =>
                {
                    b.HasOne("ACMEncuenta.ddd.Dominio.Entidades.Encuesta", "Encuesta")
                        .WithMany("ListaDeCampos")
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encuesta");
                });

            modelBuilder.Entity("ACMEncuenta.ddd.Dominio.Entidades.EncuestaCamposValor", b =>
                {
                    b.HasOne("ACMEncuenta.ddd.Dominio.Entidades.EncuestaCampos", "EncuestaCampos")
                        .WithMany()
                        .HasForeignKey("EncuestaCamposId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACMEncuenta.ddd.Dominio.Entidades.EncuestaCodigos", "EncuestaCodigos")
                        .WithMany()
                        .HasForeignKey("EncuestaCodigosEncuestaId", "EncuestaCodigosCodigoPK");

                    b.Navigation("EncuestaCampos");

                    b.Navigation("EncuestaCodigos");
                });

            modelBuilder.Entity("ACMEncuenta.ddd.Dominio.Entidades.EncuestaCodigos", b =>
                {
                    b.HasOne("ACMEncuenta.ddd.Dominio.Entidades.Encuesta", "Encuesta")
                        .WithMany()
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encuesta");
                });

            modelBuilder.Entity("ACMEncuenta.ddd.Dominio.Entidades.Encuesta", b =>
                {
                    b.Navigation("ListaDeCampos");
                });
#pragma warning restore 612, 618
        }
    }
}
